### ISSUE TITLE
Hardcoded path in run_raptorx-ss8.pl

### ISSUE THREAD

**Issue by miguelcorrea** [realbigws/RaptorX_Property_Fast#7]
Hi,

In line 3 of run_raptorx-ss8.pl RaptorX-Property is assumed to be in the home directory:
`$raptorx=$ENV{"HOME"}."/RaptorX_Property_Fast";`
If it's not (e.g. in a network filesystem) this will make it crash with the error "Failed to generate TGT file". This might be related to issue #6.

**Comment by realbigws** [comment]
Hi, Miguel.

I agree with you.

Now that the RaptorX_Property_Fast is obsoleted. Please try the new version
below:
https://github.com/realbigws/Predict_Property

In this new version, all the path issues have been solved. Also, I separate
the feature generation module to TGT_Package:
https://github.com/realbigws/TGT_Package

Please try it and let me know.

Best,
-Sheng

**Comment by miguelcorrea** [comment]
Hi Sheng,

Thanks for the heads-up.  I think it would be good to have a deprecation warning and a link to the new version in the README and the scripts.
I've already run RaptorX_Property_Fast for about 1000 sequences; should I expect changes in predictions in the new version? I'm mainly interested in predicting secondary structure and solvent accessibility.

Best,
Miguel

**Comment by realbigws** [comment]
On Mon, May 6, 2019 at 12:14 PM Miguel Correa <notifications@github.com>
wrote:

> Hi Sheng,
>
> Thanks for the heads-up. I think it would be good to have a deprecation
> warning and a link to the new version in the README and the scripts.
> I've already run RaptorX_Property_Fast for about 1000 sequences; should I
> expect changes in predictions in the new version? I'm mainly interested in
> predicting secondary structure and solvent accessibility.
>

If you're using the same protocol to generate the TGT file with the same
database (by default, it should be uniprot20_2016_02), then you shall
obtain exactly the same result between RaptorX_Property_Fast and
Predict_Property.

Thanks for your kind suggestion. I've added a WARNING message in the README
file of the RaptorX_Property_Fast package.

Best,
-Sheng

**Comment by miguelcorrea** [comment]
Thanks! With this we can close this issue.
